#!/bin/bash
# This is used only to create plugin screenshots

echo "D: 1 C: 2 U: 1 W:1 | color=#ff0000"
echo "---"
echo "Hosts: 1024"
echo "Services: 10002934"
echo "---"
echo "Host problems"
echo "kittens-a-0.internal | color=#ff0000"
echo "-- Acknowledge | href=\"#\""
echo "-- Check now | href=\"#\""
echo "---"
echo "Service problems"
echo "kittens-mysql - mysql-a-0.internal | color=#ff0000"
echo "-- Acknowledge | href=\"#\""
echo "-- Check now | href=\"#\""
echo "kittens-memcached - memcached-a-0.internal | color=#ff0000"
echo "-- Acknowledge | href=\"#\""
echo "-- Check now | href=\"#\""
echo "web-nginx - router-a-0.internal | color=#660066"
echo "-- Acknowledge | href=\"#\""
echo "-- Check now | href=\"#\""
echo "errors-in-app - kittens-app | color=#ff9900"
echo "-- Acknowledge | href=\"#\""
echo "-- Check now | href=\"#\""
echo "---"
echo "Refresh | href=\"#\""

